[project]
name = "banking-mcp-server"
version = "0.1.0"
description = "Banking MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.13.1",
    "requests>=2.32.5",
]
